apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      name: http
