{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "api-gateway.fullname" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "api-gateway.fullname" . }}
    creationPolicy: Owner
  data:
{{- range $envName, $secretName := .Values.externalSecrets.data }}
    - secretKey: {{ $envName }}
      remoteRef:
        key: {{ $secretName }}
{{- end }}
{{- end }}
