replicaCount: 3
fullnameOverride: edfp-prod-auth-service
image:
  repository: REPLACE_WITH_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/edfp-prod-auth-service
  tag: prod
config:
  ENVIRONMENT: prod
externalSecrets:
  data:
    DATABASE_URL: /edfp/prod/auth-service/database-url
    REDIS_URL: /edfp/prod/auth-service/redis-url
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
