replicaCount: 1
fullnameOverride: edfp-dev-order-service
image:
  repository: REPLACE_WITH_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/edfp-dev-order-service
  tag: dev
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_DEV_ORDER_SERVICE_IRSA_ROLE_ARN
config:
  ENVIRONMENT: dev
externalSecrets:
  data:
    DATABASE_URL: /edfp/dev/order-service/database-url
    REDIS_URL: /edfp/dev/order-service/redis-url
    ORDER_EVENTS_QUEUE_URL: /edfp/dev/order-service/order-events-queue-url
