replicaCount: 1
fullnameOverride: ""
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: payment-service
  annotations:
    eks.amazonaws.com/role-arn: ""
service:
  type: ClusterIP
  port: 8000
config:
  SERVICE_NAME: payment-service
  ENVIRONMENT: dev
  AWS_REGION: us-east-1
  PAYMENT_SUCCESS_MODE: always
  LOG_LEVEL: INFO
externalSecrets:
  enabled: true
  secretStoreName: aws-secrets-manager
  refreshInterval: 1h
  data:
    DATABASE_URL: /edfp/dev/payment-service/database-url
    NOTIFICATION_EVENTS_QUEUE_URL: /edfp/dev/payment-service/notification-events-queue-url
migration:
  enabled: true
  activeDeadlineSeconds: 900
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
probes:
  livenessPath: /health
  readinessPath: /ready
