replicaCount: 1
fullnameOverride: edfp-dev-api-gateway
image:
  repository: REPLACE_WITH_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/edfp-dev-api-gateway
  tag: dev
config:
  SERVICE_NAME: api-gateway
  ENVIRONMENT: dev
externalSecrets:
  data:
    AUTH_SERVICE_URL: /edfp/dev/api-gateway/auth-service-url
    ORDER_SERVICE_URL: /edfp/dev/api-gateway/order-service-url
    PAYMENT_SERVICE_URL: /edfp/dev/api-gateway/payment-service-url
ingress:
  host: api.dev.example.com
